name: First Workflow

on: 
 workflow_dispatch

env:
  MY_VAR: 'workflow'
 
jobs:
 build:
  env:
   MY_VAR: 'jobs'
  runs-on: ubuntu-latest
  steps:
  
   - name: Setup Java JDK
     env:
      MY_VAR: 'steps'
     run: echo '${{vars.MY_VAR}}'  
     
     

      
