name: First Workflow

on: 
 workflow_dispatch
 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
      java-version: '17'
      distribution: 'microsoft'
   - name: Info
     run: |
      echo "Github event that triggered this workflow ${{github.event_name}}"
      echo "Github SHA value is ${{github.sha}}"
