name: First Workflow

on: pull_request

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Print
     run: echo 'hello World'
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Display
     run: echo "test the step"
  
